# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MobilCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: [ 'platform=iOS Simulator,OS=14.5,name=iPhone 11 Pro' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install homebrew and appium
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install node
        echo node -v
        sh "appium"
    - name: Run app
      run: |
        python session_ios.py
