# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MobilCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: [ 'platform=iOS Simulator,OS=14.5,name=iPhone 11 Pro' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install node
      run: |
        brew install node
        echo node -v
    - name: Appium pre requisites
      run: npm install carthage
    - name: Install Appium
      run: npm install -g appium
    - name: Run Appium
      run: appium

  appium:
    runs-on: macos-latest
    steps:
    - name: Run app
      run: python session_ios.py
